type = "card"
title = "Awards"
description = "Honors and awards I have received."

[[items]]
title = "National Scholarship"
subtitle = "Ministry of Education of P.R. China"
date = "2023"


[[items]]
title = "Outstanding Graduate of Liaoning Province"
subtitle = "Education Department of Liaoning Province"
date = "2025"

[[items]]
title = "Kaggle Silver Medal (Top 5%)"
subtitle = "Optiver - Trading at the Close"
date = "2023"

[[items]]
title = "Tao Li Bread Alumni Scholarship"
subtitle = "Dalian University of Technology"
date = "2022"

[[items]]
title = "Academic Excellence & Merit Student Awards"
subtitle = "Dalian University of Technology"
date = "2022 â€” 2024"