[site]
title = "Runze Jiang"
description = "master student at the Peking University."
favicon = "/1F4AB.svg"
last_updated = "December 25, 2025"

[author]
name = "Runze Jiang"
title = "Master Student"
institution = "Peking University"
avatar = "/bio.jpg"

[social]
# Contact information (leave blank or delete to hide)

# 单个邮箱写法：
# email = "j944029213@163.com"
# 多个邮箱写法：
email = [
  "2501210087@stu.pku.edu.cn",
  "keith.jiang10@gmail.com",
  "j944029213@163.com"
]
location = "Beijing, China"
location_url = "https://maps.google.com"
location_details = [
  "Peking University, Beijing, China"
]
google_scholar = "https://scholar.google.com"
orcid = "https://orcid.org"
github = "https://github.com/keith-Jiang"
linkedin = "https://linkedin.com"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "Homepage"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Honors and Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "Projects"
type = "page"
target = "projects"
href = "/projects"

[[navigation]]
title = "Educations"
type = "page"
target = "educations"
href = "/educations"

[[navigation]]
title = "Internships"
type = "page"
target = "internships"
href = "/internships"

[[navigation]]
title = "Blogs"
type = "page"
target = "blogs"
href = "/blogs"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
