[[news]]
date = "2025-09"
content = "Started my Master's degree in Data Science at the School of Mathematical Sciences, Peking University."

[[news]]
date = "2025-06"
content = "Graduated with a BSc degree in Mathematics and Applied Mathematics from Dalian University of Technology."